[package]
name = "yeet"
version = "1.0.0"
authors = ["Ty Poorman <rust@flotts.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
